version: '3.8'

services:
  sftp-server:
    build: .
    container_name: sftp-docker-server
    ports:
      - "2222:22"
    volumes:
      - ./data:/home/sftpuser/upload
      - ./logs:/var/log
    environment:
      - SFTP_USER=sftpuser
    restart: unless-stopped
    networks:
      - sftp-network

networks:
  sftp-network:
    driver: bridge

volumes:
  sftp-data:
    driver: local